apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ei-middleware.fullname" . }}-secret
  labels:
    {{- include "ei-middleware.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secretEnv }}
  {{ $k }}: |-
    {{ $v | toString }}
  {{- end }}
