"""initial schema

Revision ID: 3b2ec71abdb1
Revises: 
Create Date: 2026-07-03 20:54:32.315519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b2ec71abdb1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_boundary_scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_label', sa.String(length=255), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('flagged_terms', sa.JSON(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consent_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sub', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.Column('consent_level', sa.String(length=64), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_sub'), 'consent_records', ['sub'], unique=False)
    op.create_table('consent_token_records',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('sub', sa.String(length=255), nullable=False),
    sa.Column('aud', sa.String(length=255), nullable=False),
    sa.Column('iss', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('context_hash', sa.String(length=64), nullable=False),
    sa.Column('context_envelope', sa.JSON(), nullable=False),
    sa.Column('policy_uri', sa.String(length=512), nullable=False),
    sa.Column('consent_level', sa.String(length=64), nullable=False),
    sa.Column('consent_version', sa.String(length=32), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index(op.f('ix_consent_token_records_sub'), 'consent_token_records', ['sub'], unique=False)
    op.create_table('dignity_ledger_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ctid_reference', sa.String(length=64), nullable=True),
    sa.Column('jti', sa.String(length=36), nullable=True),
    sa.Column('sub', sa.String(length=255), nullable=True),
    sa.Column('signal_category', sa.String(length=64), nullable=True),
    sa.Column('inference_label', sa.String(length=255), nullable=True),
    sa.Column('pdev_action', sa.String(length=64), nullable=True),
    sa.Column('decision', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.Column('context_hash', sa.String(length=64), nullable=True),
    sa.Column('previous_block_hash', sa.String(length=64), nullable=False),
    sa.Column('block_hash', sa.String(length=64), nullable=False),
    sa.Column('hmac_signature', sa.String(length=64), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('sequence')
    )
    op.create_table('egl_signal_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sub', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('tier_label', sa.String(length=64), nullable=True),
    sa.Column('signal_codes', sa.JSON(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('cognitive_load', sa.String(length=16), nullable=True),
    sa.Column('emotional_state', sa.String(length=32), nullable=True),
    sa.Column('action_risk', sa.String(length=16), nullable=True),
    sa.Column('breaker_action', sa.String(length=64), nullable=True),
    sa.Column('ledger_event_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_egl_signal_events_sub'), 'egl_signal_events', ['sub'], unique=False)
    op.create_table('launch_gate_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gate_name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('maturity_level', sa.Integer(), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pdev_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sub', sa.String(length=255), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('requested_feature', sa.String(length=255), nullable=False),
    sa.Column('decision', sa.String(length=64), nullable=False),
    sa.Column('purpose_gate', sa.String(length=16), nullable=False),
    sa.Column('dignity_gate', sa.String(length=16), nullable=False),
    sa.Column('evidence_gate', sa.String(length=16), nullable=False),
    sa.Column('veto_gate', sa.String(length=16), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('ledger_event_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdev_decisions_sub'), 'pdev_decisions', ['sub'], unique=False)
    op.create_table('policy_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.Column('decision', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_table('tar_authorizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sub', sa.String(length=255), nullable=False),
    sa.Column('inference_ref', sa.String(length=255), nullable=False),
    sa.Column('inference_recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('authorized_action', sa.String(length=255), nullable=False),
    sa.Column('action_risk', sa.String(length=16), nullable=False),
    sa.Column('escalation_allowed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reauthorized_from', sa.String(length=36), nullable=True),
    sa.Column('ledger_event_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tar_authorizations_sub'), 'tar_authorizations', ['sub'], unique=False)
    op.create_table('trajectory_evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('time_window', sa.String(length=64), nullable=False),
    sa.Column('support_mode', sa.String(length=64), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('trajectory_status', sa.String(length=64), nullable=False),
    sa.Column('attenuation', sa.String(length=16), nullable=False),
    sa.Column('proportionality', sa.String(length=16), nullable=False),
    sa.Column('contestability', sa.String(length=16), nullable=False),
    sa.Column('symmetry_of_adaptation', sa.String(length=16), nullable=False),
    sa.Column('recommended_action', sa.String(length=64), nullable=False),
    sa.Column('inputs_summary', sa.JSON(), nullable=False),
    sa.Column('ledger_event_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trajectory_evaluations')
    op.drop_index(op.f('ix_tar_authorizations_sub'), table_name='tar_authorizations')
    op.drop_table('tar_authorizations')
    op.drop_table('revoked_tokens')
    op.drop_table('policy_rules')
    op.drop_index(op.f('ix_pdev_decisions_sub'), table_name='pdev_decisions')
    op.drop_table('pdev_decisions')
    op.drop_table('launch_gate_records')
    op.drop_index(op.f('ix_egl_signal_events_sub'), table_name='egl_signal_events')
    op.drop_table('egl_signal_events')
    op.drop_table('dignity_ledger_events')
    op.drop_index(op.f('ix_consent_token_records_sub'), table_name='consent_token_records')
    op.drop_table('consent_token_records')
    op.drop_index(op.f('ix_consent_records_sub'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_table('claim_boundary_scans')
    # ### end Alembic commands ###
