apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Release.Name }}-api
    {{- include "ei-middleware.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Release.Name }}-api
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
  type: ClusterIP
