{{- if not .Values.secrets.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "ei-middleware.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  ledger-hmac-secret: {{ .Values.secrets.ledgerHmacSecret | quote }}
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
{{- end }}
